### ISSUE TITLE
add sticky header option

### ISSUE THREAD

**Issue by jeanvdr** [daniel1919-00/ng-dominus#1]
Hi,
Would be nice to add a sticky header option
Thanks

**Comment by daniel1919-00** [comment]
Hey, thanks for the suggestion.

Sticky header option added in [this commit](https://github.com/daniel1919-00/ng-dominus/commit/cdd24d6811d829bb50aeff7aebf7e15a0de5d352), unfortunately because of the way I handle overflow it only works if you use the newly added [maxHeight] input, which limits the table's height (excluding the paginator)

**Comment by jeanvdr** [comment]
Thanks +++
